test: hello-pepr-finalize failing
defenseunicorns/pepr-excellent-examples pull request #187
Opened 2024-10-30 18:48 UTC by btlghrants

Should fix the `hello-pepr-finalize` tests _AND_ the `    SyntaxError: Unterminated string in JSON at position 2180 (line 1 column 2181)` errors we've been seeing.

2024-10-30 21:46 UTC, samayer12 commented
Related to https://github.com/defenseunicorns/pepr/issues/1307

2024-10-30 22:18 UTC, samayer12 requested changes
@btlghrants does this work locally for you? The tests timed out on my end. Here's an example log message:

```
  ● finalize.ts › update, opt out of removing finalizer › triggers action and finalizer callbacks but skips removing finalizer

    thrown: Object {
      "exitcode": 1,
      "stderr": Array [
        "(node:33006) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().",
        "Support for loading ES Module in require() is an experimental feature and might change at any time",
        "(Use `node --trace-warnings ...` to show where the warning was created)",
        "File /Users/sam/code/work/pepr-excellent-examples/hello-pepr-finalize/capabilities/finalize.ts is not formatted correctly",
        "Error building module: Error: Command failed: /Users/sam/code/work/pepr-excellent-examples/node_modules/.bin/tsc --project /Users/sam/code/work/pepr-excellent-examples/hello-pepr-finalize/tsconfig.json --outdir dist",
        "    at genericNodeError (node:internal/errors:983:15)",
        "    at wrappedFn (node:internal/errors:537:14)",
        "    at checkExecSyncError (node:child_process:882:11)",
        "    at execFileSync (node:child_process:918:15)",
        "    at buildModule (/Users/sam/code/work/pepr-excellent-examples/node_modules/pepr/dist/cli.js:2569:44)",
        "    at async Command.<anonymous> (/Users/sam/code/work/pepr-excellent-examples/node_modules/pepr/dist/cli.js:2445:33) {",
        "  status: 1,",
        "  signal: null,",
        "  output: [",
        "    null,",
        "    <Buffer 63 61 70 61 62 69 6c 69 74 69 65 73 2f 66 69 6e 61 6c 69 7a 65 2e 74 73 28 37 37 2c 32 32 29 3a 20 65 72 72 6f 72 20 54 53 32 33 34 35 3a 20 41 72 67 ... 202 more bytes>,",
        "    <Buffer >",
        "  ],",
        "  pid: 33208,",
        "  stdout: <Buffer 63 61 70 61 62 69 6c 69 74 69 65 73 2f 66 69 6e 61 6c 69 7a 65 2e 74 73 28 37 37 2c 32 32 29 3a 20 65 72 72 6f 72 20 54 53 32 33 34 35 3a 20 41 72 67 ... 202 more bytes>,",
        "  stderr: <Buffer >",
        "}",
        "",
      ],
      "stdout": Array [
        "Formatting errors were found. The build will continue, but you may want to run `npx pepr format` to address any issues.",
        "capabilities/finalize.ts(77,22): error TS2345: Argument of type '(cm: V1ConfigMap) => boolean' is not assignable to parameter of type 'FinalizeAction<typeof V1ConfigMap, V1ConfigMap>'.",
        "  Type 'boolean' is not assignable to type 'void | Promise<void>'.",
        "",
      ],
    }

      11 |
      12 | describe("finalize.ts", () => {
    > 13 |   beforeAll(async () => await moduleUp(), mins(2));
         |            ^
      14 |   afterAll(async () => {
      15 |     await clean(trc)
      16 |     await moduleDown()

      at capabilities/finalize.e2e.test.ts:13:12
      at Object.<anonymous> (capabilities/finalize.e2e.test.ts:12:9)
      ```

2024-10-31 12:08 UTC, cmwylie19 commented
> @btlghrants does this work locally for you? The tests timed out on my end. Here's an example log message:
> 
> ```
>   ● finalize.ts › update, opt out of removing finalizer › triggers action and finalizer callbacks but skips removing finalizer
> 
>     thrown: Object {
>       "exitcode": 1,
>       "stderr": Array [
>         "(node:33006) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().",
>         "Support for loading ES Module in require() is an experimental feature and might change at any time",
>         "(Use `node --trace-warnings ...` to show where the warning was created)",
>         "File /Users/sam/code/work/pepr-excellent-examples/hello-pepr-finalize/capabilities/finalize.ts is not formatted correctly",
>         "Error building module: Error: Command failed: /Users/sam/code/work/pepr-excellent-examples/node_modules/.bin/tsc --project /Users/sam/code/work/pepr-excellent-examples/hello-pepr-finalize/tsconfig.json --outdir dist",
>         "    at genericNodeError (node:internal/errors:983:15)",
>         "    at wrappedFn (node:internal/errors:537:14)",
>         "    at checkExecSyncError (node:child_process:882:11)",
>         "    at execFileSync (node:child_process:918:15)",
>         "    at buildModule (/Users/sam/code/work/pepr-excellent-examples/node_modules/pepr/dist/cli.js:2569:44)",
>         "    at async Command.<anonymous> (/Users/sam/code/work/pepr-excellent-examples/node_modules/pepr/dist/cli.js:2445:33) {",
>         "  status: 1,",
>         "  signal: null,",
>         "  output: [",
>         "    null,",
>         "    <Buffer 63 61 70 61 62 69 6c 69 74 69 65 73 2f 66 69 6e 61 6c 69 7a 65 2e 74 73 28 37 37 2c 32 32 29 3a 20 65 72 72 6f 72 20 54 53 32 33 34 35 3a 20 41 72 67 ... 202 more bytes>,",
>         "    <Buffer >",
>         "  ],",
>         "  pid: 33208,",
>         "  stdout: <Buffer 63 61 70 61 62 69 6c 69 74 69 65 73 2f 66 69 6e 61 6c 69 7a 65 2e 74 73 28 37 37 2c 32 32 29 3a 20 65 72 72 6f 72 20 54 53 32 33 34 35 3a 20 41 72 67 ... 202 more bytes>,",
>         "  stderr: <Buffer >",
>         "}",
>         "",
>       ],
>       "stdout": Array [
>         "Formatting errors were found. The build will continue, but you may want to run `npx pepr format` to address any issues.",
>         "capabilities/finalize.ts(77,22): error TS2345: Argument of type '(cm: V1ConfigMap) => boolean' is not assignable to parameter of type 'FinalizeAction<typeof V1ConfigMap, V1ConfigMap>'.",
>         "  Type 'boolean' is not assignable to type 'void | Promise<void>'.",
>         "",
>       ],
>     }
> 
>       11 |
>       12 | describe("finalize.ts", () => {
>     > 13 |   beforeAll(async () => await moduleUp(), mins(2));
>          |            ^
>       14 |   afterAll(async () => {
>       15 |     await clean(trc)
>       16 |     await moduleDown()
> 
>       at capabilities/finalize.e2e.test.ts:13:12
>       at Object.<anonymous> (capabilities/finalize.e2e.test.ts:12:9)
>       ```
> ```

This is actually working for me. Thanks for reviewing this. Lets merge this and see if it fixes our pipeline and we can always revert since this is e2e

```
PASS  capabilities/finalize.e2e.test.ts (55.856 s)
  finalize.ts
    create
      ✓ triggers action and finalizer callbacks (2 ms)
    createorupdate
      ✓ triggers action and finalizer callbacks
    update
      ✓ triggers action and finalizer callbacks
    update, opt out of removing finalizer
      ✓ triggers action and finalizer callbacks but skips removing finalizer (16 ms)
    delete
      ✓ triggers action and finalizer callbacks

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        55.897 s, estimated 59 s
Ran all test suites matching /.*.e2e.test.ts/i.
```

2024-10-31 12:08 UTC, cmwylie19 approved these changes

2024-10-31 12:08 UTC, merged